### ISSUE TITLE
add docker and docker compose to DO

### ISSUE THREAD

**Issue by brandesdavid** [FreiFahren/backend#69]
> nice, then it's good to deploy from my side. the only important thing is making sure that docker + docker compose and just are available in the droplet, as well as the adjusted environment variables. i adjusted the readme accordingly :)

@brandesdavid can you check this?

_Originally posted by @johan-t in https://github.com/FreiFahren/backend/issues/65#issuecomment-2074153395_

**Comment by johan-t** [comment]
@brandesdavid please close this issue or open it in linear
